apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredReplicas
metadata:
  name: deployment-must-have-2-replicas
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    min: 2
    max: 100
