apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTrustedImages
metadata:
  name: trusted-image-repos
spec:
  parameters:
    repos:
    - "nginx"
    - "nginxinc"
    - "nginxinc/nginx"
    - "nginxinc/nginx-ingress"

