languageCode = "en-us"
name = "GeekyRyan"
baseUrl = "https://rnemeth90.github.io"
title = "GeekyRyan"
# theme = ["hugo-coder", "book"]
enableRobotsTXT = true

[pagination]
pagerSize = 10 # Added field from Coder theme

# [services]
# [services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname" # Added section from Coder theme

[markup.highlight]
style = "base16-snazzy"
noClasses = false # Added field from Coder theme

[markup.goldmark.renderer]
unsafe = true # enable raw HTML in Markdown

[params]
author = "Ryan Nemeth"
email = "ryannemeth@live.com" # used for microformats
description = "Ryan Nemeth's personal website"
keywords = "blog,developer,personal,devops"
info = ["Full Stack DevOps Engineer"]
# avatarURL = "images/bobble.jpg" #
dateFormat = "2006-01-02"
name = "GeekyRyan"
paginationSinglePost = true
style = "dark"
readMore = true # show read more button
readNextPosts = 5 # show 5 related posts, 0 by default
disableSummary = false
copyCodeButton = true # true by default
rssAsSocialIcon = true
since = 2012
rtl = false # Added from Coder theme
colorScheme = "auto" # Added from Coder theme
hideColorSchemeToggle = false # Added from Coder theme
maxSeeAlsoItems = 5 # Added from Coder theme
customCSS = [] # Added from Coder theme
customSCSS = [] # Added from Coder theme
customJS = [] # Added from Coder theme
customRemoteJS = [] # Added from Coder theme

[[params.social]]
url = "https://github.com/rnemeth90/" 
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/ryan-nemeth-b0b1504b/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 3
url = "https://rnemeth90.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml" # Added from Coder theme

[taxonomies]
category = "categories"
tag = "tags"
series = "series" # Added from Coder theme
author = "authors" # Added from Coder theme

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "TIL"
weight = 3
url = "til/"

[[languages.en.menu.main]]
name = "Projects"
weight = 4
url = "projects/"

[[languages.en.menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

# [module]
#   [[module.imports]]
#     path = "github.com/alex-shpak/hugo-book"
#
#   [[module.imports.mounts]]
#     source = "themes/book/layouts"
#     target = "layouts/notes"
#
