apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://64.227.144.17:5000/validate
  name: webhook
contexts:
- context:
    cluster: webhook
  name: webhook-context
current-context: webhook-context
