apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: five
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VabWwyWlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUpLZGxyK2pCUFJZdXdHenFiaEY4bmx0R3ZhMmpYeGRnNEVuMWZwRml5VmlTcWpKCnM3L0Q3L2RSMjlHbVZtQkgrbHR1NFpHYjFUMXhtTXZVV1RrcVdlaXpSUk1qZlpmRTMxMzRiRzc0U00zZGtsc08Kb09YNmhNMWtPbWlHb1RwT2djYVhPcVUxUlptZ2xQYUhTRE51QTQ5cFNqejh6L0s5WHdYRFVqSzVhZG1aUExaWgpBOFhEa0FTZ2FDYlV1SFdQWmlqb1VPT3hwNU9NdlRoamVhQzNFeDFQWTljUTJib1hnMXhpRmZCZnNqM09obGpECmdMU2xnNGdlZ3NlZWhtWHlldW9iVkZZak92d3o2dVZ6QnZ3blpBWGJQbEF4NDRycGpCRnZKSFVTWElDdVdRbDQKWjQrV3p1RlhiSWpEVnVrSEhWQUoyelJEYzZ0U3FyVXZkTEl5QTdjQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQWRkSG4ydFVwYmdBV1kzNWR3V3QrOWk3RmhjUGxmdkhNL29FK1hxRjZvWmlnUU9kMSt1UndpCk54aHJpV2dOdithMFBpV2ZCanF3dWJCL2tXcG94NC9KUlBsTm9NNGJTLzVhZ3drSGVsRkYveFlpMkRhVzlpNDgKLy9aWU5vU1pHQUJRWnhBZ2xTaG82dlVSQ2w4ZWlwZ2dGTDNLQi9OTVRaMEFxbFhJY3NCanJPU1M4cVZ1dXVQZgpYOEU1aFlUWGFxa0t6ZHFTRE0vNUxrZjBsc3lVR3JHVU12VFFjcXVibWVrc2FEWFdSUHVUbGdpN2xGWVFHZGhxCmwxd3hZandBOVNCQzZLVUdXZnpCeW83RFduVEh0UzhGa3RlODhVbEwreDR3dHhMcDZWLzlFR2ZSeWhuaDh1Z1EKeWhrYlVjaGJHaGd3ZldpY0ZkcERFZ0lvdys3eDhGcGwKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth

