apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apparmor-runtimedefault-pod
  name: apparmor-runtimedefault-pod
  namespace: apparmor-lab
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1h
    image: busybox:1.28
    name: busybox-security-context
    securityContext:
      appArmorProfile:
        type: RuntimeDefault
