apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: seccomp-restricted-pod
  name: seccomp-restricted-pod
  namespace: seccomp
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: "profiles/restricted.json"
  containers:
  - image: busybox
    name: secure-pod
    resources: {}
    command: ["sh", "-c", "sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
