apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: immutable-pod
  name: immutable-pod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1h
    image: ubuntu:latest
    name: immutable-pod
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /data/test
      name: empty
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: empty
    emptyDir: {}
status: {}
