apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-env-var
  name: pod-with-env-var
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1h
    image: busybox:1.28
    name: pod-with-env-var
    env:
    - name: MY_VAR
      value: "Hello from the environment"
