apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-list
  name: service-list
  namespace: t21
spec:
  serviceAccount: api-caller
  containers:
  - image: alpine/curl:3.14
    name: service-list
    resources: {}
    command:
    - /bin/sh
    - -c
    - "while true; do wget -O- http://kubernetes.default.svc/api/v1/namespaces/t21/services; sleep 5; done"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: api-caller
  namespace: t21
  resourceVersion: "0"
  uid: 1c2f3b4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6
