apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: t21
  name: resource-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "watch", "list"]

