apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: me
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1VqQ0NBVG9DQVFBd0RURUxNQWtHQTFVRUF3d0NiV1V3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUURFZmZmMXRicWhRNTFmOWVpZ3I4RytKRVRTYjZlYnBzeHArYWpMUlZjM0g3L1k3akFQCmMzcktqanJuY0J3UFhabWNOS09hS052OC90MlNqQnJEOGxjM2JGdjJ6cFhuNVRDaWE2alNVNGdZTHVKTjJSMEoKb20zYTg2eXRGTnJzbnVFakdOd2NJL2JZRjNKQmZNRlBuYlh5WnhlY3B2S0ZTK2gxeE13UzhLSE44VWNlbDNpTgpuUGwzZlU5a09DVzZueCtmS01UZmQxTVZ4citOSmpOT0FpQmdUWWRCb2pxL1Jxay9qUit6aFFMSWhBMFpFdy82ClZUOFNkMzZ3RWhzTFdjaHBQRWk4YnpqMVdGTUlPSGhyRWI5RTRGNmhVbzZNU1JtbmRiUnM5WWJjc2tuTDl5U0EKR1locU9lUXFjSUpRWEZMWTdkRjZ4M2s4eHZuWld1V3VPaS83QWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQWhwQk45VktNdU0za2prc3gzdzliR1Qxd0RzMkszV3ZnMmU4dTYzWmtQbEJnaVF4b1FFSDQ2Ukc1CjV0cGd5bGtQN0ZHeWhrWUhaTmtYNzVuYmFvZ1lTVGN4cWpBYWExZTNBdThkNW9RVFAvR2l1SjNXVGZ4RmF3SXgKSTdheFVFYWt2RDdrMG0zam54dlV4KzFabEg3c2ZTV1VsSGtVd24rcUcyTkcrWWdaWU9NelB0Tnl4cXdtYXZXdAphVGp2VG5rNFRRV2kvTWMvMWloL2V2ODlZajFHeDN3TnZwTVNhUWdTYno0T3FENTRLbDZWdnNTUTMydXdPK05PCkd6aWQxbEx5OTM0aUMrOWJzbCtSYWdxOHBXQkpRSnJ6MjZydzZGenE1ZW9ycVNWaVBVdnVHaGVPL1pnWm1xYm8KWXlsY3RZTjNIZCtSNEdBRHp1eWN0Wk1vL0dHUm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth

