apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-one
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RiMjVsTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBemM5S1dOYnF2Yy9YVkZhQ0prY1lOd1JNaC9iWHRjU3VCNGZ2Z3dXSnNvZEV5OVJoCjVLRGxtOHNBZXdtM0FzVEthN2E3bHk5c3FXTXViajZiR01yUjVOZXVPYWcxT3RLVFFCYzdyRkIxMHMvQnVYOWIKWXFteDBTNnVybU54VjFNdkwrQXVMYmRvaW1waWVXQytQZk84VlJkTm1LdEREUktMWk9vQ3N0bFA5TEIrakFMNgpEbWpFVEloTkVodnZsdHp1eGtTREZ4VzNFeTFpTC9kZFhhNHpiaTh3S2pVMmNTZ1k3Y241NFJPV3M1bUlNZmFlCjMwbmFTbHljc0hYWXRQZnBDY0Rkb0NKNk9TREdGRDdMQnBlbkw5TnJWK0RzU0VXWjNTbGIxVjhCblVEeENhRDEKYUMwbXBoVlA2VWRpQnFOQ3BTUDFXNk9ROXlFendMZUplTmZ5endJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFEU1Z6K1FVQisrNWV1OHA4RFc3ZkxQekZ5RmxHUjZkZmtKSmdkWXJPK3h2TkVrREpTQW9LYklBCmJVZitwcVF6Yi8vQWVOUFFna3ZTU011YTBUZkI1V1NKaWpzbk1YS2JQdXdUOEpBLzdtZ3BzM01sdHcrNG9RWVUKMFo0TTJrRzlJSEVkSC9ScElIZmx2M3JMTThyNjVuYngyYkVzMTQwTDBvYldRZURUWU9KdUFZYzRyRHdTckFLbQprQlBwblcwUG92a05ObjdZM2tCV3pPaC9ORlVCMm5sbWJUd28vSE1DZlBpNEF6ODZnbi92TGd6ditoWTVJMlZwCndBMnRadnNtR0V1dlZTSXRVWmpRQ0VUL0FDQi93U0RpeHNuaWVKSldsb3cxNmtLRSt0cFFPSWRZM0wwQlVWM2EKUGtzbGJ3Wm1CTVNpRk9DTHhGdll2T0xYUStJOWNocz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth

