apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-security-context
  name: busybox-security-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1h
    image: busybox:1.28
    name: busybox-security-context
    securityContext:
      allowPrivilegeEscalation: false
    resources: {}
    volumeMounts:
    - mountPath: /data/test
      name: empty
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: empty
    emptyDir: {}
status: {}
