apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
  labels:
    app: proxy
spec:
  containers:
    - name: proxy-container
      image: busybox
      command: [ "sleep", "infinity" ]
    - name: proxy
      image: ubuntu
      command:
      - /bin/bash
      - -c
      - apt update && apt upgrade -y && apt install -y iptables && iptables -L && sleep 1d
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  restartPolicy: Always
