apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - server-app
    env: 
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: api-basic-auth
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: api-basic-auth
          key: password
    image: nginx:1.18.0
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
