apiVersion: v1
kind: Pod
metadata:
  name: runasuser-pod
  labels:
    app: runasuser
spec:
  containers:
  - name: runasuser-container
    image: busybox
    command: [ "sleep", "infinity" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
