[book]
title = "notebook"
authors = ["ryan nemeth"]
language = "en"
src = "."

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
fold.enable = true

# search settings
[output.html.search]
enable = true
limit-results = 50
expand = true
# boost-title = 2.0
# boost-hierarchy = 1.5
# boost-paragraph = 1.0
heading-split-level = 3
use-boolean-and = false

